### ISSUE TITLE
Missing attributions

### ISSUE THREAD

**Issue by SaschaWillems** [BobLChen/VulkanDemos#109]
It looks like you have copied over a lot of my samples, down to using the same shaders, setup and even some models that I created for them.

So at least some attribution would be great, esp. as the models that I created for my own samples are not meant for distribution or free usage.

**Comment by BobLChen** [comment]
Thanks for your samples, it helps me to study vulkan more efficient. I am also ready to add Copyright of your models and shaders because of i am busy to build samples, but no copied for samples and setup.

**Comment by BobLChen** [comment]
> It looks like you have copied over a lot of my samples, down to using the same shaders, setup and even some models that I created for them.
> 
> So at least some attribution would be great, esp. as the models that I created for my own samples are not meant for distribution or free usage.

Please check my commit and find some need attributions i missed.

https://github.com/BobLChen/VulkanDemos/commit/47bf00819b34eb74023e788a4f61d73559334519
https://github.com/BobLChen/VulkanDemos/commit/61f089370f29f86a3c3035a951e1f1b831ac2789
https://github.com/BobLChen/VulkanDemos/pull/111/commits/dee3f26fedc30f0f91a1d803d09b137d6f419bcf

**Comment by SaschaWillems** [comment]
You're lacking attributions for pretty much all the models and textures you have included. Not only the ones from me, so it would be a good idea to check for licenses for each asset you provide with your samples.

I see that you e.g. use the same textures as I do in your indirect draw example, and those are afaik at least partially made by Hugues Mueller.

So you may want to check https://github.com/SaschaWillems/Vulkan/blob/master/CREDITS.md and compare with what asset you're using.

**Comment by BobLChen** [comment]
solved
