### ISSUE TITLE
fatal error: 'vulkan/vulkan.h' file not found

### ISSUE THREAD

**Issue by dandingol03** [BobLChen/VulkanDemos#169]
compile on android studio
error below
`
In file included from /Users/wangjunjie/Documents/Github/VulkanDemos/Engine/Monkey/Demo/DVKBuffer.cpp:1:
In file included from /Users/wangjunjie/Documents/Github/VulkanDemos/Engine/Monkey/Vulkan/VulkanCommon.h:4:
In file included from /Users/wangjunjie/Documents/Github/VulkanDemos/Engine/Monkey/Vulkan/VulkanRHI.h:5:
In file included from /Users/wangjunjie/Documents/Github/VulkanDemos/Engine/Monkey/Vulkan/VulkanPlatform.h:14:
In file included from /Users/wangjunjie/Documents/Github/VulkanDemos/Engine/Monkey/Vulkan/Android/VulkanPlatformDefines.h:3:
/Users/wangjunjie/Documents/Github/VulkanDemos/Engine/Monkey/Vulkan/Android/VulkanAndroidPlatform.h:10:10: fatal error: 'vulkan/vulkan.h' file not found
`

**Comment by BobLChen** [comment]
i am working on it.

**Comment by BobLChen** [comment]
it maybe fixed on this commit d14992d6f08b1a0c1ed06f9d9ae1b6da189d1108
