### ISSUE TITLE
请教一下，报错了

### ISSUE THREAD

**Issue by ruanyx** [BobLChen/VulkanDemos#49]
请教一下，报错了
![图片](https://user-images.githubusercontent.com/9652284/62004421-797cbd80-b157-11e9-9fbb-31b332672af0.png)

**Comment by BobLChen** [comment]
你直接checkout master主干，能够编译吗？我看了一下你这报错的行数已经跟我的对应不上了。

**Comment by ruanyx** [comment]
![图片](https://user-images.githubusercontent.com/9652284/62206542-a2ee5100-b3c4-11e9-8d6e-8d48b74fbabd.png)
![图片](https://user-images.githubusercontent.com/9652284/62206588-b994a800-b3c4-11e9-85ca-624ca5137931.png)
应该是这两处

**Comment by BobLChen** [comment]
https://github.com/BobLChen/VulkanDemos/blob/master/document/BUILD_Windows.md
跟着这个教程一模一样来一遍

**Comment by BobLChen** [comment]
这个问题是由于你是通过DownloadZIP获取的源码进行构建编译的，所以会出现这个问题。
使用**git clone https://github.com/BobLChen/VulkanDemos.git**获取源码就不会出现这个问题了。
